spring:
  data:
    mongodb:
      username: admin
      password: admin
      database: customerdb
      host: localhost
      port: 27017
      authentication-database: admin
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: paymentGroup,orderGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringSerializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: orderConfirmation:com.saas.order_service.dto.clientDto.OrderConfirmation,paymentConfirmation:com.saas.payment_service.notification.PaymentNotificationRequest
  mail:
    host: localhost
    port: 1025
    username: saas
    password: saas
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

server:
  port: 8088

