spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/order_db
    username: postgres
    password: 7012
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: orderConfirmation:com.saas.order_service.dto.clientDto.OrderConfirmation




server:
  port: 8086

application:
  config:
    customer-service-url: http://localhost:8082/api/v1/customers
    product-service-url: http://localhost:8085/api/v1/products
    payment-service-url: http://localhost:8087/api/v1/payments