spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/product_db
    username: postgres
    password: 7012
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    baseline-description: "Initial version"
    username: postgres
    password: 7012

server:
  port: 8085

